name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  GITHUB_TOKEN:  # id of input
    description: 'Access Token'
    required: true
    default: 'World'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node16'
  main: 'dist/index.js'